### ISSUE TITLE
Support Multi language

### ISSUE THREAD

**Issue by alexanmtz** [alexanmtz/truppie#11]
Make the website supports English by marking the template and all the strings separate in languages YAML file. Now the website support Portuguese with a lot of strings already extracted, it's just a matter that continue this work.

What is part of this issue:
- Extract all strings in a YAML file (one in portuguese and another in english that is already in progress).
- The strings will be extracted from controllers, templates, models representations, email templates 

What does not include
- Translate the content
- It's a payment platform and the currency is not part of the scope

Requirements
- The changes will be ran into our continuous integration that run tests to verify that everything works (https://travis-ci.org/alexanmtz/truppie)
- Your code will be reviewed by me (alexanmtz@gmail.com) that is owner of this platform

You have to create a fork and run the project locally as we explain in the **README** file and our guides.

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gerenciador de textos e idiomas](https://trello.com/c/6A2uNPkf/139-gerenciador-de-textos-e-idiomas)

**Comment by alexanmtz** [comment]
As the project has a lot of strings, we will restrict for this milestone the most important ones and that affects the end user.

The scope will be:

1. Welcome views (all)
2. Tours views and Controllers (show, confirm, confirm_presence)
3. Contact view and Controller

Keep in mind that any partial used in this templates should be converted to i18n too.

**Comment by alexanmtz** [comment]
#14

**Comment by taharushain** [comment]
Following scope has been achieved, now only 'welcome views' need to be converted to i18n

- Tours views and Controllers (show, confirm, confirm_presence)
- Contact view and Controller

Kindly fix the tests and let me know if I could do anything else.

**Comment by alexanmtz** [comment]
@taharushain it's really nice the work until now, I fixed the tests to reflect the translations and you can proceed with the Welcome views, and after done and tests passing, the build will create an app from the PR to test, so I can validate your version before goes to production and then we're done, thanks!

**Comment by taharushain** [comment]
Check my latest PR, I've done my part.

**Comment by alexanmtz** [comment]
Thanks @taharushain , it was just a little error that I easily fixed, :1st_place_medal:
