### ISSUE TITLE
Replacing Fixtures with Factory Girl

### ISSUE THREAD

**Issue by charithhewage** [alexanmtz/truppie#12]
Hi Alex,
As there are many advantages using factories rather than fixtures, I would suggest you to use [FactoryGirl](https://github.com/thoughtbot/factory_girl_rails) with truppie. Moving to factories in this stage will be more helpful in the future  (time, easiness etc...).

**Comment by alexanmtz** [comment]
Hey @charithhewage, I've used Factories before and I kept simple this time and there are more than 400 assertions using the Rails testing library with the fixtures and it works well, I don't see a real motivation to use Factories in this case
