### ISSUE TITLE
Versão do ruby

### ISSUE THREAD

**Issue by heliohead** [alexanmtz/truppie#20]
Qual a versão do ruby está sendo usada no projeto, não existe um arquivo .ruby-version e nem uma linha ex. ruby '2.3.0' no Gemfile

**Comment by alexanmtz** [comment]
está certo @heliohead, a versão do ruby atual é `ruby 2.2.3p173` e seria melhor defini-la no `Gemfil` e para garantir que vai instalar a mesma versão em qualquer ambiente.

Você pode abrir um pull request com essa modificação?

**Comment by alexanmtz** [comment]
You did it, great! @heliohead #21 :1st_place_medal:

**Comment by heliohead** [comment]
💣  Testes falharam quando fixei o ruby para 2.2.3 #24

**Comment by 3fernandez** [comment]
@alexanmtz, acredito que esta issue pode ser fechada, pois já foi incluído o arquivo **.ruby-version** no root do projeto, que define a versão usada. 😏
