### ISSUE TITLE
Perfil de um guia cadastrado aparecer no Truppie Places

### ISSUE THREAD

**Issue by alexanmtz** [alexanmtz/truppie#22]
Esta é uma tarefa bastante simples para quem está começando e quer se familiarizar com a plataforma, com um ambiente Rails e como contribuir com projetos no Github.

O [Truppie](http://truppie.com) Places são páginas na [Truppie](http://truppie.com) sobre os lugares, como essa aqui: [https://truppie.com/wheres/1-ilha-de-gigoia](https://truppie.com/wheres/1-ilha-de-gigoia)
(ainda está no início do desenvolvimento)

Esta tarefa consiste em listar um Card do perfil de um guia (que já tem em várias partes do site, inclusive na principal) que foi cadastrado naquele local, ou seja, que ele oferece passeios de um determinado local.

![screen shot 2017-10-15 at 5 18 59 pm](https://user-images.githubusercontent.com/88840/31586126-00807614-b1cd-11e7-8d5d-29267b61d09c.png)

Quando o guia se cadastra [(https://truppie.com/welcome/organizer)](https://truppie.com/welcome/organizer), um dos passos é saber o local onde o guia oferece passeios, e assim temos vinculado um local com o model `where` determinando este local.

Na página do local (todo local cadastrado se tornar uma página do [Truppie Places](https://truppie.com/welcome/user) através do cadastro de um model chamado `background` vinculado a um local.

Sendo assim, se tiverem guias deste local, listar logo após a seção 'Experiences` o card do perfil do guia que pode ser incluído em: [https://github.com/alexanmtz/truppie/blob/master/app/views/layouts/_organizer_card.html.erb](https://github.com/alexanmtz/truppie/blob/master/app/views/layouts/_organizer_card.html.erb)

![screen shot 2017-10-15 at 4 31 09 pm](https://user-images.githubusercontent.com/88840/31585689-6a5f84b4-b1c6-11e7-9230-1b2340b61d16.png)

Se precisar de qualquer ajuda e tirar qualquer dúvida, fique a vontade e esta tarefa é uma ótima oportunidade de aprender com um projeto real e poder trabalhar em outras tarefas posteriormente.

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Guia de um determinado local aparecer no Truppie Places](https://trello.com/c/y6cgZ7s4/499-guia-de-um-determinado-local-aparecer-no-truppie-places)

**Comment by amandaclarck** [comment]
Posso pegar essa, @alexanmtz? Ainda não sei como funciona muito bem, sou júnior e gostaria de me familiarizar com o projeto :)

**Comment by alexanmtz** [comment]
Sim @amandaclarck , qualquer ajuda que precisar vamos discutindo aqui, a idéia é essa mesmo! Boa sorte!

**Comment by amandaclarck** [comment]
@alexanmtz Legal! Mandei um email pra você pra pedir mais infos, aí acredito que possamos continuar nossa conversa lá :). Obrigada

**Comment by renatoramiro** [comment]
Gostaria de ajudar também se ainda tiver alguma tarefa.

**Comment by alexanmtz** [comment]
Logo estarei postando mais @renatoramiro , você pode acompanhar e ajudar com feedback quando a @amandaclarck enviar um pull request ;-)

**Comment by alexanmtz** [comment]
olá @amandaclarck , Como anda a tarefa? Precisa de ajuda?

**Comment by amandaclarck** [comment]
@alexanmtz eu comecei a configurar o ambiente ontem pois faz um tempo que não mexo com RoR e meu pc eu havia formatado. Mas Ruby, rails e git já instalei, hoje já forko o projeto e toco o barco

**Comment by amandaclarck** [comment]
@alexanmtz Fui rodar o projeto e deu erro (anexo). Pode me ajudar? 
![captura de tela de 2017-10-21 23-22-22](https://user-images.githubusercontent.com/11525900/31857200-daf7b026-b6b6-11e7-93a6-25fbce65ccd0.png)

**Comment by amandaclarck** [comment]
@alexanmtz Estou tentando configurar o projeto e rodando o rake test e o rails s deu o erro (anexo). Pode me ajudar?
![a](https://user-images.githubusercontent.com/11525900/31857266-818df674-b6b8-11e7-9a15-bdb9e61179ee.png)

**Comment by alexanmtz** [comment]
@amandaclarck você fez a migration, executou `rake db:migrate`?

Você precisa ter uma conexão local com o `postgre`, tá com isso configurado?

já deu um `bundle install` e viu que está com as dependências instaladas?

**Comment by amandaclarck** [comment]
Executei sim o rake db:migrate, e dá stack level too deep. Eu tenho o postgresql configurado pro meu usuário e pro postgresql. Já dei bundle install sim

**Comment by alexanmtz** [comment]
execute `which ruby` e me diz o que aparece por favor. Me parece com versão do Rails que você usa. Você usa o `rvm`?

**Comment by amandaclarck** [comment]
Eu tô usando o rbenv, @alexanmtz. O which ruby retorna /home/amanda/.rbenv/shims/ruby e o rails -v retorna  Rails 4.2.5.1

**Comment by alexanmtz** [comment]
você vai precisar para este ambiente ter um ruby versão `2.2.3` e deve estar usando outra versão. Tem uma issue #20 que coloca a versão no Gemfile mas por algum motivo os testes falham e vai ajudar nesta parte, mas até lá você precisa ter no rbenv a versão 2.2.3 do Ruby para esta aplicação.

**Comment by amandaclarck** [comment]
@alexanmtz Realmente, era a versão do Ruby. O que aconteceu é que a versão que eu tinha era a 2.4.2 e aí fiz o que você falou e instalei a 2.2.3, porém quando fui rodar o rake db:create foi mostrado um erro relacionado à versão do ruby, que não era compatível com o rake db:create (algo assim) e aí pediu pra eu instalar a versão 2.2.6. Agora estou com a 2.2.6 e tá tudo ok, já consegui criar o banco, as tabelas e estou rodando o projeto. Demorei pra responder porque cada vez que instala uma nova versão do ruby eu tive que reinstalar as gems

**Comment by viniciusfmaciel** [comment]
Também gostaria de ajudar no projeto. Deixo me apresentar. Sou Vinicius, tenho 8 anos de experiência em .Net e recentemente estou aprendendo Rails. Vejo que muita coisa do Asp Net MVC vem do Rails, isso é muito bom. Se precisar de alguma ajudar pode contar comigo. Muito obrigado. ;)

**Comment by alexanmtz** [comment]
Brigado @viniciusfmaciel , pode ir acompanhando aqui e se quiser já ir se familiarizando rodar o projeto que estarei nesta semana disponibilizando novas issues para quem quiser contribuir.

**Comment by viniciusfmaciel** [comment]
@alexanmtz consegui rodar o projeto aqui no Linux. Maravilha. Esperando issues hehe. Valeu

**Comment by alexanmtz** [comment]
@viniciusfmaciel adicionei várias, uma galera já pegou mas se quiser tem algumas de colaboração para começar e espero poder colocar mais para ajudar.

**Comment by amandaclarck** [comment]
@alexanmtz Posso pedir ajuda para essa tarefa? Não sei se é valido pedir por aqui... É bem simples (para quem manja rs). Nao estou sabendo alinhar os cards (e aproveito para perguntar se fiz certo de colocar o card do lado da tour). Eles ficam assim (anexo). Aliás, se eu puder mencionar alguém para me ajudar com isso eu menciono também, aí posso te aliviar também :). Código aqui https://gist.github.com/amandaclarck/827e5ea9f07e0404ab6acbf697d561cc
![truppie](https://user-images.githubusercontent.com/11525900/32138712-5a2ca0ea-bc16-11e7-8023-d758bcb434fb.png)

**Comment by alexanmtz** [comment]
Olá @amandaclarck , sem problema em pedir ajuda por aqui, é pra isso mesmo o intuito das tarefas. Também não se importe com o tempo, essas são justamente também melhorias que são muito boas de ter, mas que podem esperar.

E bom ir sim enviando antes se tiver qualquer dúvida pois no fim pode ser totalmente diferente do que era esperado e a gente ajusta de acordo com as discussões.

Você pode enviar também o que você está trabalhando numa branch remota e assim posso rodar o projeto completo a partir da sua versão.

Mas tudo bem também enviar um gist. Vou dar uma olhada e comentar lá.

**Comment by amandaclarck** [comment]
Oi, @alexanmtz. Obrigada pela ajuda. Fiz um PR agora com as alterações que você sugeriu no gist e espero que seja aprovado. Fico no aguardo :+1:

**Comment by alexanmtz** [comment]
#39

**Comment by alexanmtz** [comment]
@amandaclarck Seu Pull Request foi aprovado e você agora é uma contribuidora :-)

O Heroku está em manutenção e logo as suas mudanças entrarão em produção.

Obrigado  e que bom que gostou e você está mandando bem, acho que está pronta para novos desafios ;-)

**Comment by amandaclarck** [comment]
Obrigada, @alexanmtz! Fico muito feliz! Gostaria de pegar uma próxima tarefa. Pode me sugerir alguma?

**Comment by alexanmtz** [comment]
@amandaclarck devo criar novas issues esta semana para quem gostaria de aprender e te aviso esta semana.

**Comment by amandaclarck** [comment]
@alexanmtz Ok. Fico no aguardo!
