### ISSUE TITLE
Um mapa listando as truppies cadastradas - R$ 180,00

### ISSUE THREAD

**Issue by alexanmtz** [alexanmtz/truppie#23]
Na seção [http://explore.truppie.com/](http://explore.truppie.com/), logo após o título "Explore e experimente", exibir um mapa de largura completa do Google com os passeios cadastrados `tour` sendo exibidos em um balão. 

![jif1j](https://user-images.githubusercontent.com/88840/31585804-3b3f2d86-b1c8-11e7-82bd-e6758cfb9b48.jpg)

Seguir este screenshot como modelo. Será exibida a foto, valor, título e descrição do evento no evento e uma ação "Reservar" (com a tradução correspondente "Book now")

Já temos um modelo de mapas no arquivo: [https://github.com/alexanmtz/truppie/blob/master/app/assets/javascripts/places.js](https://github.com/alexanmtz/truppie/blob/master/app/assets/javascripts/places.js) e temos um no projeto já configurado para renderizar mapas, como pode ser observado na página de um `tour` : [https://truppie.com/tours/1-passeio-de-barco-pela-ilha-da-gigoia](https://truppie.com/tours/1-passeio-de-barco-pela-ilha-da-gigoia)

Colocar um ícone também no local representado, mas ao invés de um hotel colocar o ícone `ticket`, usamos o [Font-awesome](http://fontawesome.io/icons/).

### Insira no template um mapa do Google com largura completa
Insira um mapa do Google com largura completa no template e um arquivo `js` correspondente que irá ser responsável por renderizar o mapa. Certifique-se que este JS só irá prosseguir se encontrar o  elemento do mapa. Você pode usar jQuery se quiser

### Obtenha os eventos e seu attribute `where`
O model `tour`, responsável por cada evento da Truppie possuem o atributo `where` que contém todas informações do local, inclusive do `id` do Google Place, que caso não esteja disponível poderá ser localizado pela Latitude e longitude do local.

Sendo assim, temos como critério de aceitação:

- [ ] Quando uma atividade é cadastrada por um guia, ela está referenciada a um local e ela passa a ser exibida no mapa com a sua localização na página http://explore.truppie.com
- [ ] Se ela não tiver determinação do local identificado, adquirir localização por latitude e longitude, e se ainda sim não conseguir, não exibir no mapa :-(

![screen shot 2017-10-15 at 5 27 59 pm](https://user-images.githubusercontent.com/88840/31586195-44e6aa52-b1ce-11e7-9a3b-04020ceb4746.png)

### Considerações sobre a plataforma:

- Usamos o [Bootstrap](https://v4-alpha.getbootstrap.com), sendo assim todos os padrões da interface seguem o seu padrão
- O código será validado e os testes automatizados serão realizados para certificar-se de a mudança não afete de forma não prevista outras partes da plataforma
- Você receberá comentários sobre suas mudanças
- Temos testes automatizados para validar as funcionalidades, então você deverá seguir este padrão criando testes automatizados que valida o que foi desenvolvido.

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

```
 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail
```

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa, que entrarei em contato para obter os detalhes para realizar o pagamento
2. [Faça um fork do projeto](http://desenvolvimentoparaweb.com/miscelanea/como-fazer-fork-de-um-projeto-no-github/)
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo **ambiente para testes** será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 
10. Quando o _Pull Request_ for finalizado, o **pagamento é enviado**

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 

Se quiser se familiarizar com o funcionamento de projetos de software livre, tem este [excelente guia do Tableless](https://tableless.com.br/contribuindo-em-projetos-open-source-com-o-github/)

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Truppies no mapa](https://trello.com/c/whAtT3oR/483-truppies-no-mapa)

**Comment by hugohernani** [comment]
Legal! Tenho interesse, @alexanmtz! :)

**Comment by alexanmtz** [comment]
Obrigado pelo interesse @hugohernani , o @leospaula irá ficar com ela e logo estarei postando mais.

**Comment by alexanmtz** [comment]
#25

**Comment by alexanmtz** [comment]
Pull request integrado e transferência realizada @leospaula
