### ISSUE TITLE
Não salva foto que foi inserida no modo visualização - R$ 40,00

### ISSUE THREAD

**Issue by alexanmtz** [alexanmtz/truppie#27]
![screen shot 2017-10-18 at 10 58 33 pm](https://user-images.githubusercontent.com/88840/31742465-fb801ac4-b457-11e7-8605-c4d5cdb984fd.png)

Quando um `tour` (que chamamos de truppie) é salva sem foto, ele vai para a página do evento criado e tem a chance de enviar uma foto de capa do evento. A foto então é escolhida e ele pode salvar as mudanças. Por algum motivo o botão `salvar mudanças` não está enviando os dados e assim salvando a foto.

### Como chegar no cenário descrito

 - Criar uma conta de usuário
 - Criar uma conta de guia clicando em **sou guia**
 - Criar uma truppie na página de adminstração do guia no menu _Truppies -> criar truppies_
 - A Truppie precisa estar sem foto
 - Um botão de enviar foto irá aparecer na página do evento
 - Escolher uma foto
 - Um botão **Salvar mudanças** irá aparecer`
 - Clicar em **Salvar mudanças** não tem a ação de enviar o formulário e salvar as mudanças

![screen shot 2017-10-18 at 10 56 59 pm](https://user-images.githubusercontent.com/88840/31742468-fb9c82c2-b457-11e7-9a1f-d4fc5a75fcc0.png)

Critério de aceitação:

- [ ] Quando o usuário tentar salvar as mudanças quando enviar uma foto, enviar o formulário, salvar a foto e ir novamente para a página do evento com a foto salva

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

```
 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail
```

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa
2. [Faça um fork do projeto](http://desenvolvimentoparaweb.com/miscelanea/como-fazer-fork-de-um-projeto-no-github/)
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo **ambiente para testes** será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 
10. Quando o _Pull Request_ for finalizado, o **pagamento é enviado**

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 

Se quiser se familiarizar com o funcionamento de projetos de software livre, tem este [excelente guia do Tableless](https://tableless.com.br/contribuindo-em-projetos-open-source-com-o-github/)

**Comment by 3fernandez** [comment]
Opa @alexanmtz blza? Posso pegar essa task?

**Comment by alexanmtz** [comment]
Olá @3fernandez , pode pegar sim! O que precisar é só falar e boa sorte. 👍

**Comment by 3fernandez** [comment]
@alexanmtz a conta do guia precisa estar "verificada" para poder criar um Tour("Truppie")?
Pois preenchi o form e tentei cria-lá clicando em "Salvar truppie" e "Salvar e publicar", mas nenhuma das opções cria de fato. E a mesma não retorna erro algum.
Tem algo que eu não saiba ou esteja fazendo errado?

**Comment by alexanmtz** [comment]
A conta do guia não precisa estar verificada para criar @3fernandez , o que pode estar ocorrendo, se você olhar nos logs, é que o Rails insiste em dar o erro de `unpermited params` mesmo estando no controller definindo todos parâmetros e recentemente forcei com `permit!`

Quando você está como admin, você pode criar Tour através da rota `/tours/new`, é por lá que você está criando, ou pela interface do usuário?

**Comment by 3fernandez** [comment]
Então @alexanmtz, estou criando pela interface do usuário, clicando em "Sou Guia" e em seguida em "Truppies". E a partir da dashboard, clico em "Criar uma truppie agora", em seguida "adicionar truppie", e após preencher o formulário e submeter, ela me redireciona para root_path com uma flash message: "Ei, você não está autorizado a entrar nesta página".

**Comment by alexanmtz** [comment]
você está com a última versão @3fernandez? Se obteve a última atualização isto pode ter resolvido, caso contrário, tente configurar você como admin com os passos que coloquei na tarefa:

E ai se não funcionar pela forma normal, é possível se você colocar seu email de cadastro numa variável de ambiente.

Como se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:
```
 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail
```

E com isso você poderia também criar através de `/tours`

Tente essas possibilidades e me diga se funcionou. Acho que eu restringi algumas rotas por acidente para adminstradores. Tente ver no controller `tours_controller` se ele está restringindo somente aos admins.

Qualquer coisa é só falar, abraços e boa sorte!

**Comment by alexanmtz** [comment]
o seu pull request foi integrado @3fernandez , favor enviar seus dados bancários para transferência através do e-mail ola@truppie.com.

Obrigado pela contribuição. Sua mudança já está no ar!

**Comment by 3fernandez** [comment]
Vlw @alexanmtz, mandarei os dados bancários no email indicado e estarei aguardando por mais issues. 😎

**Comment by alexanmtz** [comment]
transferido e enviado comprovante @3fernandez
