### ISSUE TITLE
Na página de adicionar truppie, os campos que aceitam tags submetem o formulário - R$ 60,00

### ISSUE THREAD

**Issue by alexanmtz** [alexanmtz/truppie#28]
Usamos o `taginput` (ótimo plugin para jQuery) para inserir tags de itens (como tags, o que inclui num evento etc), e ele funcionava bem até então. Agora, no momento em que os dados de um `tour` (que chamamos de truppie) é preenchido, as tags quando inseridas e pressionado _Enter_, o formulário é enviado. O plugin deveria evitar a submissão do formulário. Isto de fato acontece em outros lugares onde este campo está presente, como na adminstração de um `tour` (`tours -> edit`)

![screen shot 2017-10-18 at 11 25 38 pm](https://user-images.githubusercontent.com/88840/31743532-bb3132ba-b45b-11e7-806b-ea12027ab23b.png)

### Como chegar no cenário descrito

 - Criar um usuário
 - Criar um perfil de guia no item do menu principal _Sou guia_
 - Com o seu perfil de guia, ir em _Truppies -> criar truppie_
 - Tentar preencher tags no campo de tags (assim como outros campos onde o tagsinput é aplicado) e verificar que o formulário é enviado.

Critério de aceitação:

- [ ] Não enviar o formulário com os dados quando apertamos enter ao inserir uma nova tag no campo

### Considerações sobre a plataforma:

- A plataforma tem vários lugares com esse campo e somente nesta seção o formulário está sendo enviado de forma indevida

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

```
 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail
```

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa, que entrarei em contato para obter os detalhes para realizar o pagamento
2. [Faça um fork do projeto](http://desenvolvimentoparaweb.com/miscelanea/como-fazer-fork-de-um-projeto-no-github/)
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo **ambiente para testes** será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 
10. Quando o _Pull Request_ for finalizado, o **pagamento é enviado**

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 

Se quiser se familiarizar com o funcionamento de projetos de software livre, tem este [excelente guia do Tableless](https://tableless.com.br/contribuindo-em-projetos-open-source-com-o-github/)

**Comment by jcserracampos** [comment]
Posso ficar com esta?

**Comment by alexanmtz** [comment]
@jcserracampos , pode sim! Eu tentei várias possibilidades e nenhuma funcional, vai ser muito bom ter uma outra visão, qualquer dúvida é só falar!

**Comment by alexanmtz** [comment]
Olá @jcserracampos , algum progresso?

**Comment by jcserracampos** [comment]
@alexanmtz Desculpa a demora. Estou terminando de checar umas possibilidades. Até amanhã eu devo fazer o PR.

**Comment by alexanmtz** [comment]
e ai @jcserracampos, alguma luz? 🤞

**Comment by alexanmtz** [comment]
Vou disponibilizar esta tarefa novamente, pois é um bug em produção que precisa ser corrigido. Então quem quiser encarar se manifeste 🔢

**Comment by tauanlemos** [comment]
Posso pegar essa?

**Comment by alexanmtz** [comment]
sim @tauanlemos ! Me dê um retorno assim que tiver uma luz.

**Comment by tauanlemos** [comment]
Você pode me confirmar só qual outra área usa o plugin corretamente? Na parte de editar tour notei o mesmo comportamento.

**Comment by alexanmtz** [comment]
Sua PR foi integrada @tauanlemos , excelente trabalho! Em alguns minutos seu código entrará em produção e mais um bug resolvido!

Por favor envie um e-mail para ola@truppie.com com os dados bancários para transferência
