### ISSUE TITLE
Colocar contato de telefone no perfil do guia - R$ 20,00

### ISSUE THREAD

**Issue by alexanmtz** [alexanmtz/truppie#32]
Esta é uma tarefa simples para acrescentar o telefone do guia na página do perfil se ele estiver cadastrado este dado. Também aparecer o ícone do whatsapp que leva ele diretamente para o chat.

![screen shot 2017-10-28 at 7 46 55 pm](https://user-images.githubusercontent.com/88840/32137036-e215a32e-bc18-11e7-88bd-4026517ff8c4.png)

### Como chegar no cenário descrito

 - Ir para a página de um guia. Ex: [https://truppie.com/organizers/2-7-cantos-do-mundo](https://truppie.com/organizers/2-7-cantos-do-mundo)

Critério de aceitação:

- [ ] Se o guia preenche o número do telefone, exibir na página do perfil o número do telefone com um ícone para o whatsapp que leva o usuário ao chat.

### Considerações sobre a plataforma:

- Os ícones são criados usando o [Font-Awesome](http://fontawesome.io/)

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

```
 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail
```

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa, que entrarei em contato para obter os detalhes para realizar o pagamento
2. [Faça um fork do projeto](http://desenvolvimentoparaweb.com/miscelanea/como-fazer-fork-de-um-projeto-no-github/)
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo **ambiente para testes** será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 
10. Quando o _Pull Request_ for finalizado, o **pagamento é enviado**

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 

Se quiser se familiarizar com o funcionamento de projetos de software livre, tem este [excelente guia do Tableless](https://tableless.com.br/contribuindo-em-projetos-open-source-com-o-github/)

### Como ter um pull request aceito e integrado da forma correta no projeto

Para que seu Pull Request seja aceito sem maiores problemas e integrado diretamente para que possa ir para produção você deve sempre estar integrado com o master do projeto, **sempre usando rebase como padrão**.

Se tiver dúvidas como fazer isto dá uma olhada aqui [neste post](http://www.arruda.blog.br/programacao/dicas-de-git-integrando-um-branch-no-master-rebase-ou-merge/)

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 o

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Botar mais contatos no perfil do guia (whatsapp, telefone)](https://trello.com/c/MDGzcsFG/548-botar-mais-contatos-no-perfil-do-guia-whatsapp-telefone)

**Comment by 3fernandez** [comment]
@alexanmtz vou pegar essa, já que a outra já foi pega. #LOL

**Comment by alexanmtz** [comment]
Pode pegar essa logo depois da que você já está fazendo @3fernandez , pois esta é bem mais simples.

**Comment by alexanmtz** [comment]
o @3fernandez já está em outra tarefa que necessita de uma solução mais apurada.

Quem for iniciante e quiser pegar esta tarefa é uma boa chance de se familiarizar com o código e aprender com uma tarefa simples.

**Comment by alexanmtz** [comment]
@3fernandez quer pegar essa? Amanhã lhe faço a transferência da que foi aprovada, se pegar esta farei de ambas se conseguir finalizar amanhã.

**Comment by alexanmtz** [comment]
gostaria de pegar essa @3fernandez ?

**Comment by 3fernandez** [comment]
Opa @alexanmtz, posso resolver sim.

**Comment by 3fernandez** [comment]
@alexanmtz, você exemplificou como chegar ao perfil de um guia, mas o exemplo não aplica ao meu ambiente. Gostaria de saber que "atributo" aplico no final da url para localizar um perfil específico.

**Comment by alexanmtz** [comment]
@3fernandez, você pode criar um perfil de guia, mas para não precisar fazer todos os passos você pode dar um `rake db:seed` e ir em `/organizers/` e clicar em _exibir_ para cair na página do perfil do guia que foi preenchido com o seed do Rails. Qualquer dúvida, é só falar!

**Comment by 3fernandez** [comment]
@alexanmtz seria algo como isso?
![screen shot 2017-11-27 at 17 07 45](https://user-images.githubusercontent.com/3707769/33284281-a9867d0a-d395-11e7-9696-7c2f12c03a08.png)

Caso o número de WhatsApp esteja cadastrado.

**Comment by alexanmtz** [comment]
Sim, exatamente!

**Comment by alexanmtz** [comment]
Pull request integrado e transferência realizada e comprovante enviada para o seu e-mail @3fernandez . Obrigado mais uma vez pela contribuição 🥇

**Comment by pissulin** [comment]
URL base: https://truppie.com/tours/6-cachoeira-da-fumaca-por-baixo-chapada-diamantina-ba

![image](https://user-images.githubusercontent.com/29817040/74434541-65718280-4e41-11ea-801d-c788896de97a.png)

Notei que em algumas partes do site o perfil do guia não apresenta o telefone com o logo do whatsApp.

**Comment by alexanmtz** [comment]
@pissulin neste caso são guias que não cadastraram nenhum telefone
