### ISSUE TITLE
Data e hora do evento não salva corretamente - R$ 80,00

### ISSUE THREAD

**Issue by alexanmtz** [alexanmtz/truppie#36]
Os eventos são criados usando um calendário em Javascript que escreve num campo hidden de data e hora o que foi escolhido pelo usuário para início e fim do evento. Porém na hora de exibir o evento está aparecendo com datas e horários divergentes.

Isto acontece devido a unificação de data entre o javascript e o ruby ser necessária. Tentei realizar as conversões colocando todos em UTC mas mesmo assim não deu certo. Sendo assim, para solucionar este problema pode ser preciso trabalhar com timezones. 

### Como chegar no cenário descrito

 - Criar uma conta como guia
 - Ir em _Criar truppie_
 - Escolher as datas de saída e retorno
 - Visualizar evento
 - As datas dos eventos não correspondem sempre a data correta

Critério de aceitação:

- [ ] A data escolhida na hora de cadastrar o evento sempre corresponder de forma correta a data que aparece na visualização, bem como salvar a data corretamente no banco.

### Considerações sobre a plataforma:

- Existe um javascript de calendário que irá se transformar num componente, mas no momento ele é um script na página com algumas limitações.
- As datas escolhidas são salvas em campos para serem salvas no servidor quando o evento é salvo pelo guia.

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

```
 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail
```

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa, que entrarei em contato para obter os detalhes para realizar o pagamento
2. [Faça um fork do projeto](http://desenvolvimentoparaweb.com/miscelanea/como-fazer-fork-de-um-projeto-no-github/)
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo **ambiente para testes** será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 
10. Quando o _Pull Request_ for finalizado, o **pagamento é enviado**

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 

Se quiser se familiarizar com o funcionamento de projetos de software livre, tem este [excelente guia do Tableless](https://tableless.com.br/contribuindo-em-projetos-open-source-com-o-github/)

### Como ter um pull request aceito e integrado da forma correta no projeto

Para que seu Pull Request seja aceito sem maiores problemas e integrado diretamente para que possa ir para produção você deve sempre estar integrado com o master do projeto, **sempre usando rebase como padrão**.

Se tiver dúvidas como fazer isto dá uma olhada aqui [neste post](http://www.arruda.blog.br/programacao/dicas-de-git-integrando-um-branch-no-master-rebase-ou-merge/)

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 o

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Definir hora do evento pelo timezone do usuário](https://trello.com/c/mQk1PT5n/524-definir-hora-do-evento-pelo-timezone-do-usu%C3%A1rio)

**Comment by 3fernandez** [comment]
@alexanmtz posso dar uma olhada nisto?

**Comment by alexanmtz** [comment]
Pode pegar sim @3fernandez, esta tarefa é um pouco urgente, pois é um bug grave que atrapalha as datas dos eventos e que já quebrei bastante a cabeça por isto, então prefiro que pegue ela antes de qualquer outra.

O componente de calendário que criei para ele está um pouco bagunçado, mas vou extrai-lo num componente separado aqui: [https://github.com/alexanmtz/trip-range](https://github.com/alexanmtz/trip-range). Se tiver interesse poderá contribuir posteriormente.

Qualquer dúvida é só falar.

**Comment by 3fernandez** [comment]
Show de bola, vou priorizar.

**Comment by alexanmtz** [comment]
Não esqueça desta vez @3fernandez que sempre que obter as atualizações do projeto usar sempre `rebase` a partir da sua branch, para não termos maiores dores de cabeça na integração. Infelizmente por conta de um merge eu perdi suas indentações :-(

**Comment by 3fernandez** [comment]
Aah poxxa 😞... Blza então.

**Comment by alexanmtz** [comment]
Comprovante de transferência enviado e código já integrado como foi conversado @3fernandez . Obrigado pela contribuição!

**Comment by 3fernandez** [comment]
Opa @alexanmtz, muito obrigado. Está sendo legal pegar essas issues e discutir soluções consigo, estarei atento pra pegar mais. 🤘
