### ISSUE TITLE
Atualizar os textos em inglês

### ISSUE THREAD

**Issue by alexanmtz** [alexanmtz/truppie#37]
Revisar os textos que precisam ser traduzidos no arquivo: [https://github.com/alexanmtz/truppie/blob/master/config/locales/en.yml](https://github.com/alexanmtz/truppie/blob/master/config/locales/en.yml)

Para saber qual o texto correto, usar os [textos em português](https://github.com/alexanmtz/truppie/blob/master/config/locales/pt-BR.yml) como referência.

Esta é uma boa oportunidade de treinar a contribuição, rodar o projeto e praticar o inglês, pois teremos a @laurasette revisando que não deixará passar nenhum erro.

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa, que entrarei em contato para obter os detalhes para realizar o pagamento
2. [Faça um fork do projeto](http://desenvolvimentoparaweb.com/miscelanea/como-fazer-fork-de-um-projeto-no-github/)
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo **ambiente para testes** será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 

Se quiser se familiarizar com o funcionamento de projetos de software livre, tem este [excelente guia do Tableless](https://tableless.com.br/contribuindo-em-projetos-open-source-com-o-github/)

### Como ter um pull request aceito e integrado da forma correta no projeto

Para que seu Pull Request seja aceito sem maiores problemas e integrado diretamente para que possa ir para produção você deve sempre estar integrado com o master do projeto, **sempre usando rebase como padrão**.

Se tiver dúvidas como fazer isto dá uma olhada aqui [neste post](http://www.arruda.blog.br/programacao/dicas-de-git-integrando-um-branch-no-master-rebase-ou-merge/)

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 o

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Atualizar textos em inglês](https://trello.com/c/IIPBn6Yt/543-atualizar-textos-em-ingl%C3%AAs)

**Comment by amandaclarck** [comment]
Eu gostaria de pegar essa depois que finalizasse a minha, mas não sei se pode :). Inclusive, estou trabalhando na minha nesse exato momento @alexanmtz

**Comment by alexanmtz** [comment]
Prefiro que você termine primeiro @amandaclarck a tarefa que você está fazendo, mas logo depois pode pegar sim, e se precisar de qualquer coisa posso ajudar no que for preciso para tirar suas dúvidas. Que bom, espero que esteja indo tudo bem :-)

**Comment by amandaclarck** [comment]
Perfeito. Obrigada @alexanmtz

**Comment by lenilsonjr** [comment]
Também tenho interesse nessa aqui. 

@amandaclarck se importa se eu ficar com esta?

**Comment by amandaclarck** [comment]
@lenilsonjr Imagina. Vai que é tua :)

**Comment by alexanmtz** [comment]
Obrigado @lenilsonjr pela contribuição
