### ISSUE TITLE
Marcação de um passo a passo para orientar o guia a completar o cadastro - R$ 90,00

### ISSUE THREAD

**Issue by alexanmtz** [alexanmtz/truppie#38]
O processo de cadastro de um guia é um dos maiores desafios que enfrentamos para atrair os clientes a usarem a plataforma para oferecem seus passeios. Estamos criando um sistema que dá total autonomia a eles, sendo assim ele consegue preencher dados do seu perfil que será visto pelos seus clientes e cadastrar seus dados bancários e pessoais para poder receber diretamente na sua conta.

Após o cadastro na Truppie como guia (através de [http://guia.truppie.com](http://guia.truppie.com)) ele cai em seu perfil. A partir daí, exibir um componente de passo a passo para certificar que ele está seguindo os passos para verificar sua conta.

![screen shot 2017-10-28 at 8 39 59 pm](https://user-images.githubusercontent.com/88840/32137441-4093fd22-bc20-11e7-86e4-96881cf6d1ed.png)

Este componente pode ser usado do [CodePen](https://codepen.io/bronsrobin/pen/dKqcf).

Cada passo, diferente de como consta no exemplo terá um link que irá direcionar ao passo que está descrito.

Ele conterá os passos (os nomes dos passos não interessa muito, pois deverá ter só uma referência para os textos marcados para internacionalização):

1. Perfil - vai para: `https://truppie.com/organizers/nome-do-guia/profile_edit`
Verificação: a mesma da barra do perfil, ou seja, já temos métodos que validam

2. Conta Pessoal - vai para: `https://truppie.com/organizers/nome-do-guia/account_edit`
Verificação: a mesma da barra do perfil, ou seja, já temos métodos que validam

3. Dados Bancários - vai para: `https://truppie.com/organizers/nome-do-guia/bank_account_edit`
Verificação: a mesma da barra do perfil, ou seja, já temos métodos que validam

4. Criar uma truppie - vai para: `https://truppie.com/organizers/nome-do-guia/guided_tour`
Verificação: Se existe algum `tour` para aquele guia

Quando todos os dados estiverem preenchidos e contas verificadas e truppies criadas não exibir o componente mais.

Colocar um botão _verificar depois_ que esconde este componente e que muda para um botão _verificar agora_, que exibe novamente.

### Como chegar no cenário descrito

 - Criar uma nova conta de guia

### Parte 2: Colocar os links para cada passo e estado de cada um como mostrado no componente no [CodePen](https://codepen.io/bronsrobin/pen/dKqcf) de acordo com os métodos de verificações que já são usados em outras partes da interface.

Critério de aceitação:

- [ ] Aparecer lista de passos a completar na página do perfil e na página da conta do guia
- [ ] Marcar com o check de acordo como design referenciado aqui para cada passo completado
- [ ] Exibir botão de _completar depois_ que esconde componente, mas que permaneça um botão em que ele pode abrir novamente para verificar os passos (o estado pode ser gravado no `localStorage` )

### Considerações sobre a plataforma:

- Você pode utilizar totalmente o código do [CodePen](https://codepen.io/bronsrobin/pen/dKqcf) e criar um componente com os seus respectivos templates, javascript e scss em arquivos separados.

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

```
 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail
```

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa, que entrarei em contato para obter os detalhes para realizar o pagamento
2. [Faça um fork do projeto](http://desenvolvimentoparaweb.com/miscelanea/como-fazer-fork-de-um-projeto-no-github/)
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo **ambiente para testes** será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 
10. Quando o _Pull Request_ for finalizado, o **pagamento é enviado**

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 

Se quiser se familiarizar com o funcionamento de projetos de software livre, tem este [excelente guia do Tableless](https://tableless.com.br/contribuindo-em-projetos-open-source-com-o-github/)

### Como ter um pull request aceito e integrado da forma correta no projeto

Para que seu Pull Request seja aceito sem maiores problemas e integrado diretamente para que possa ir para produção você deve sempre estar integrado com o master do projeto, **sempre usando rebase como padrão**.

Se tiver dúvidas como fazer isto dá uma olhada aqui [neste post](http://www.arruda.blog.br/programacao/dicas-de-git-integrando-um-branch-no-master-rebase-ou-merge/)

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 o

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Passo a passo quando o guia se cadastrar](https://trello.com/c/Hae9BwYJ/546-passo-a-passo-quando-o-guia-se-cadastrar)

**Comment by hugohernani** [comment]
Também tenho interesse nessa task, @alexanmtz

**Comment by alexanmtz** [comment]
Pode ficar com esta @hugohernani também e veja qual das duas você prefere dar prioridade

**Comment by alexanmtz** [comment]
@hugohernani, seu pull request foi aprovado e já está em produção, o pagamento foi realizado e o comprovante enviado. Mais uma vez obrigado pela colaboração!

**Comment by Ljdgb** [comment]
Ainda encontra-se disponível?

**Comment by alexanmtz** [comment]
@Ljdgb esta já foi integrada mas teremos novas para esta semana

**Comment by alexanmtz** [comment]
@Ljdgb adicionei novas tarefas, veja qual te interessa: https://github.com/worknenjoy/truppie/issues
