### ISSUE TITLE
Não salva os campos Tags e Idiomas falados na criação e edição de uma atividade

### ISSUE THREAD

**Issue by mthais** [alexanmtz/truppie#48]
Verificar os campos "Tags" e "Idiomas falados" na criação e edição de uma atividade, pois os mesmos não estão gravando os dados.

### Como chegar no cenário descrito

 - Entrar na página principal
 - Ir em Área do guia
 - Criar uma conta de guia
 - Clicar na opção truppies
 - Ir na opção criar nova truppie
 - Preencher todos os campos
 - Clicar em Salvar e publicar 
 - Clicar em editar truppie 
 - Os campos Tag e Idiomas falados não foram salvos.

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa, que entrarei em contato .
2. [Faça um fork do projeto]
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo *ambiente para testes* será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍

**Comment by hugohernani** [comment]
@alexanmtz Se quiser posso consertar isso.

**Comment by hugohernani** [comment]
Como essa issue estava parada há um tempinho eu criei esta **PR** @alexanmtz > https://github.com/alexanmtz/truppie/pull/51

**Comment by alexanmtz** [comment]
Issue resolvida pelo @hugohernani 🥇 e integrada ao master

Muito obrigado pela contribuição, a solução ficou ótima!
