### ISSUE TITLE
Opção Área de login - Não exibe nenhuma validação para o usuário

### ISSUE THREAD

**Issue by mthais** [alexanmtz/truppie#53]
Quando o usuário insere suas informações e não está de acordo com o sistema, o sistema da reload na página e não exibe nenhuma mensagem de validação.

### Como chegar no cenário descrito

 - Entrar na página principal
 - Clicar no botão "Entrar"
 - Inserir Email e senha incorretos
 - O sistema da reload na página e não exibe nenhuma mensagem de validação.

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa, que entrarei em contato .
2. [Faça um fork do projeto]
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo *ambiente para testes* será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍

**Comment by Maycon-Rodrigues** [comment]
Opa, posso fazer essa task Alexandre?

**Comment by alexanmtz** [comment]
Fala @Maycon-Rodrigues, pode sim cara, qualquer dúvida só falar!

**Comment by alexanmtz** [comment]
Pull request integrado e issue resolvida, muito obrigado pela contribuição @Maycon-Rodrigues !

@mthais , pode verificar em produção, por favor?

**Comment by alexanmtz** [comment]
#58
