### ISSUE TITLE
Não entra em contato com o Guia quando o usuário que tem interesse não está logado

### ISSUE THREAD

**Issue by alexanmtz** [alexanmtz/truppie#59]
O Pull Request 

[Add feature do users show interest in a past tour](https://github.com/alexanmtz/truppie/pull/47)

Possibilita que o usuário demonstre interesse em eventos passados.

Só que ele ainda não cobre o cenário de demonstrar interesse em um evento quando ele não está logado.

<img width="1307" alt="screen shot 2017-12-21 at 10 09 00 pm" src="https://user-images.githubusercontent.com/88840/34279986-9c4d62c0-e69b-11e7-95e4-1c2f9c592008.png">

### Como chegar no cenário descrito

 - Ir na página principal
 - Escolher algum evento que já passou
 - Para eventos passados, o usuário que não está logado não tem nenhuma ação quando clica no botão **Tenho interesse**.

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

```
 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail
```

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa, que entrarei em contato para obter os detalhes para realizar o pagamento
2. [Faça um fork do projeto](http://desenvolvimentoparaweb.com/miscelanea/como-fazer-fork-de-um-projeto-no-github/)
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo **ambiente para testes** será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 

Se quiser se familiarizar com o funcionamento de projetos de software livre, tem este [excelente guia do Tableless](https://tableless.com.br/contribuindo-em-projetos-open-source-com-o-github/)

### Como ter um pull request aceito e integrado da forma correta no projeto

Para que seu Pull Request seja aceito sem maiores problemas e integrado diretamente para que possa ir para produção você deve sempre estar integrado com o master do projeto, **sempre usando rebase como padrão**.

Se tiver dúvidas como fazer isto dá uma olhada aqui [neste post](http://www.arruda.blog.br/programacao/dicas-de-git-integrando-um-branch-no-master-rebase-ou-merge/)

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 o

**Comment by cleicar** [comment]
@alexanmtz tenho interesse nessa tarefa

**Comment by alexanmtz** [comment]
Pode começar @cleicar ! Está contigo. Qualquer dúvida é só falar!

**Comment by alexanmtz** [comment]
@cleicar chegou a ver meus comentários sobre o seu pull request?

**Comment by cleicar** [comment]
@alexanmtz Sim! Desculpe a ausência, eu estava viajando de férias nesse início de ano. Mas agora voltei a ativa, vou atualizar meu PR ainda hoje.

**Comment by cleicar** [comment]
@alexanmtz acabei de atualizar o PR. Aguardo feedback.

**Comment by alexanmtz** [comment]
@cleicar agora a solução está adequada e seu pull request foi integrado. Obrigado pela contribuição!
